export const colors = [
    { name: "Água-marinha média", hex: "#7FFFD4" },
    { name: "Água", hex: "#00FFFF" },
    { name: "Alizarina", hex: "#E32636" },
    { name: "Amarelo", hex: "#FFFF00" },
    { name: "Amarelo esverdeado", hex: "#ADFF2F" },
    { name: "Amarelo queimado", hex: "#DAA520" },
    { name: "Âmbar", hex: "#FFBF00" },
    { name: "Ameixa", hex: "#DDA0DD" },
    { name: "Ametista", hex: "#9966CC" },
    { name: "Areia", hex: "#F4A460" },
    { name: "Aspargo", hex: "#87A96B" },
    { name: "Azul", hex: "#0000FF" },
    { name: "Azul ardósia", hex: "#6A5ACD" },
    { name: "Azul ardósia claro", hex: "#8470FF" },
    { name: "Azul ardósia escuro", hex: "#483D8B" },
    { name: "Azul ardósia médio", hex: "#7B68EE" },
    { name: "Azul areado", hex: "#5F9EA0" },
    { name: "Azul aço", hex: "#4682B4" },
    { name: "Azul aço claro", hex: "#B0C4DE" },
    { name: "Azul bebê", hex: "#89CFF0" },
    { name: "Azul Bic", hex: "#1F75FE" },
    { name: "Azul Brilhante", hex: "#0096FF" },
    { name: "Azul cadete", hex: "#536872" },
    { name: "Azul camarada", hex: "#6082B6" },
    { name: "Azul celeste brilhante", hex: "#00BFFF" },
    { name: "Azul claro", hex: "#ADD8E6" },
    { name: "Azul cobalto", hex: "#0047AB" },
    { name: "Azul céu", hex: "#87CEEB" },
    { name: "Azul céu claro", hex: "#87CEFA" },
    { name: "Azul céu profundo", hex: "#0080FF" },
    { name: "Azul escuro", hex: "#00008B" },
    { name: "Azul flor de milho", hex: "#6495ED" },
    { name: "Azul força aérea", hex: "#5D8AA8" },
    { name: "Azul furtivo", hex: "#1F305E" },
    { name: "Azul Jeans", hex: "#5DADEC" },
    { name: "Azul manteiga", hex: "#ACE5EE" },
    { name: "Azul marinho", hex: "#000080" },
    { name: "Azul meia-noite", hex: "#191970" },
    { name: "Azul médio", hex: "#0000CD" },
    { name: "Azul petróleo", hex: "#004F98" },
    { name: "Azul real", hex: "#4169E1" },
    { name: "Azul royal", hex: "#4169E1" },
    { name: "Azul serenity", hex: "#B3CEE5" },
    { name: "Azul tiffany", hex: "#93e8ea" },
    { name: "Azul turquesa", hex: "#00CED1" },
    { name: "Azul violeta", hex: "#8A2BE2" },
    { name: "Azul Náutico", hex: "#1a3271" },
    { name: "Açafrão", hex: "#F4C430" },
    { name: "Bege", hex: "#F5F5DC" },
    { name: "Beringela", hex: "#4F2F4F" },
    { name: "Blush", hex: "#FFB6C1" },
    { name: "Bordô", hex: "#800020" },
    { name: "Borgonha", hex: "#800020" },
    { name: "Branco", hex: "#FFFFFF" },
    { name: "Bronze", hex: "#CD7F32" },
    { name: "Caramelo", hex: "#C68E17" },
    { name: "Cardo", hex: "#D8BFD8" },
    { name: "Carmesim", hex: "#DC143C" },
    { name: "Carmim", hex: "#960018" },
    { name: "Castanho avermelhado", hex: "#8B4513" },
    { name: "Castanho claro", hex: "#D2691E" },
    { name: "Cenoura", hex: "#ED9121" },
    { name: "Cereja", hex: "#DE3163" },
    { name: "Cereja Hollywood", hex: "#F400A1" },
    { name: "Champanhe", hex: "#F7E7CE" },
    { name: "Chocolate", hex: "#7B3F00" },
    { name: "Chumbo", hex: "#71797E" },
    { name: "Ciano", hex: "#00FFFF" },
    { name: "Ciano escuro", hex: "#008B8B" },
    { name: "Cinza", hex: "#808080" },
    { name: "Cinza ardósia", hex: "#708090" },
    { name: "Cinza ardósia claro", hex: "#778899" },
    { name: "Cinza ardósia escuro", hex: "#2F4F4F" },
    { name: "Cinza claro", hex: "#D3D3D3" },
    { name: "Cinza escuro", hex: "#A9A9A9" },
    { name: "Cinza fosco", hex: "#696969" },
    { name: "Cobre", hex: "#B87333" },
    { name: "Coral", hex: "#FF7F50" },
    { name: "Coral claro", hex: "#F08080" },
    { name: "Couro", hex: "#AB7A3C" },
    { name: "Caqui escuro", hex: "#BDB76B" },
    { name: "Creme", hex: "#FFFDD0" },
    { name: "Dainise", hex: "#98777B" },
    { name: "Dourado", hex: "#FFD700" },
    { name: "Dourado escuro", hex: "#B8860B" },
    { name: "Escarlate", hex: "#FF2400" },
    { name: "Estampado", hex: "#FFFFFF" },
    { name: "Feldspato", hex: "#FDD5B1" },
    { name: "Fendi", hex: "#E6BE8A" },
    { name: "Ferrugem", hex: "#B7410E" },
    { name: "Fuligem", hex: "#3B3B3B" },
    { name: "Fumê", hex: "#848884" },
    { name: "Fúcsia", hex: "#AE2491" },
    { name: "Gelo", hex: "#F0F8FF" },
    { name: "Goiaba", hex: "#F08E80" },
    { name: "Grafite", hex: "#383838" },
    { name: "Grená", hex: "#6C0116" },
    { name: "Herbal", hex: "#2E8B57" },
    { name: "Hortênsia", hex: "#7B68C6" },
    { name: "Índigo", hex: "#4B0082" },
    { name: "Jade", hex: "#00A86B" },
    { name: "Jambo", hex: "#FF4500" },
    { name: "Jabuti preto", hex: "#2F2F2F" },
    { name: "Laranja", hex: "#FFA500" },
    { name: "Laranja escuro", hex: "#FF8C00" },
    { name: "Lavanda", hex: "#E6E6FA" },
    { name: "Lilás", hex: "#C8A2C8" },
    { name: "Limão", hex: "#32CD32" },
    { name: "Linho", hex: "#FAF0E6" },
    { name: "Listrada", hex: "#FFFFFF" },
    { name: "Madeira", hex: "#DEB887" },
    { name: "Magenta", hex: "#FF00FF" },
    { name: "Magenta escuro", hex: "#8B008B" },
    { name: "Malva", hex: "#E0B0FF" },
    { name: "Marfim", hex: "#FFFFF0" },
    { name: "Marrom", hex: "#800000" },
    { name: "Marrom amarelado", hex: "#B8860B" },
    { name: "Marrom claro", hex: "#A0522D" },
    { name: "Marrom rosado", hex: "#BC8F8F" },
    { name: "Marrom sela", hex: "#8B4513" },
    { name: "Marsala", hex: "#964F4C" },
    { name: "Mescla", hex: "#B8B8B8" },
    { name: "Mostarda", hex: "#FFDB58" },
    { name: "Naval", hex: "#000080" },
    { name: "Mel", hex: "#FFAE42" },
    { name: "Nude", hex: "#E3BC9A" },
    { name: "Ocre", hex: "#CC7722" },
    { name: "OffWhite", hex: "#FAF9F6" },
    { name: "Oliva", hex: "#808000" },
    { name: "Oliva escura", hex: "#556B2F" },
    { name: "Oliva parda", hex: "#6B8E23" },
    { name: "Orquídea", hex: "#DA70D6" },
    { name: "Orquídea escura", hex: "#9932CC" },
    { name: "Orquídea média", hex: "#BA55D3" },
    { name: "Ouro", hex: "#FFD700" },
    { name: "Palha", hex: "#E8D9B3" },
    { name: "Pele", hex: "#FFE4C4" },
    { name: "Pérola", hex: "#F0EAD6" },
    { name: "Pêssego", hex: "#FFDAB9" },
    { name: "Pink", hex: "#FFC0CB" },
    { name: "Prata", hex: "#C0C0C0" },
    { name: "Preto", hex: "#000000" },
    { name: "Preto Riscado", hex: "#1C1C1C" },
    { name: "Púrpura", hex: "#800080" },
    { name: "Púrpura média", hex: "#9370DB" },
    { name: "Quantum", hex: "#2E2E2E" },
    { name: "Risca de giz", hex: "#F5F5F5" },
    { name: "Rosa", hex: "#FFC0CB" },
    { name: "Rosa barbie", hex: "#f53f94" },
    { name: "Rosa bebê", hex: "#FFB7C5" },
    { name: "Rosa brilhante", hex: "#FF69B4" },
    { name: "Rosa chá", hex: "#F4C2C2" },
    { name: "Rosa Chiclete", hex: "#FC6C85" },
    { name: "Rosa chocante", hex: "#FC0FC0" },
    { name: "Rosa claro", hex: "#FFCCD5" },
    { name: "Rosa forte", hex: "#FF1493" },
    { name: "Rosa profundo", hex: "#E75480" },
    { name: "Rosa seco", hex: "#E8ADAA" },
    { name: "Rosa Shock", hex: "#E100E1" },
    { name: "Rose", hex: "#FF007F" },
    { name: "Roxo", hex: "#800080" },
    { name: "Rútilo", hex: "#6A1B9A" },
    { name: "Salmão", hex: "#FA8072" },
    { name: "Salmão claro", hex: "#FFA07A" },
    { name: "Salmão escuro", hex: "#E9967A" },
    { name: "Siena", hex: "#A0522D" },
    { name: "Sépia", hex: "#704214" },
    { name: "Telha", hex: "#B8553A" },
    { name: "Terracota", hex: "#E2725B" },
    { name: "Tiedye", hex: "#FFFFFF" },
    { name: "Tiffany", hex: "#0ABAB5" },
    { name: "Tomate", hex: "#FF6347" },
    { name: "Turquesa", hex: "#40E0D0" },
    { name: "Turquesa escura", hex: "#00827F" },
    { name: "Turquesa média", hex: "#48D1CC" },
    { name: "Urucum", hex: "#E34234" },
    { name: "Uva", hex: "#6F2DA8" },
    { name: "Verde", hex: "#008000" },
    { name: "Verde água", hex: "#66CDAA" },
    { name: "Verde amarelado", hex: "#9ACD32" },
    { name: "Verde bandeira", hex: "#009B3A" },
    { name: "Verde claro", hex: "#90EE90" },
    { name: "Verde escuro", hex: "#006400" },
    { name: "Verde esmeralda", hex: "#20655e" },
    { name: "Verde floresta", hex: "#228B22" },
    { name: "Verde jade", hex: "#00A86B" },
    { name: "Verde lima", hex: "#32CD32" },
    { name: "Verde grama", hex: "#7CBA3D" },
    { name: "Verde militar", hex: "#4B5320" },
    { name: "Verde musgo", hex: "#3C341F" },
    { name: "Verde oliva", hex: "#808000" },
    { name: "Verde-azulado", hex: "#008080" },
    { name: "Verde Petroléo", hex: "#046865" },
    { name: "Verde tiffany", hex: "#0ABAB5" },
    { name: "Verde menta", hex: "#9fbdab"},
    { name: "Vermelho", hex: "#FF0000" },
    { name: "Vermelho escuro", hex: "#8B0000" },
    { name: "Vermelho Ferrari", hex: "#FF2800" },
    { name: "Vermelho indiano", hex: "#CD5C5C" },
    { name: "Vermelho violeta", hex: "#C71585" },
    { name: "Vermelho violeta médio", hex: "#DB7093" },
    { name: "Vermelho violeta pálido", hex: "#E8B4CD" },
    { name: "Violeta", hex: "#EE82EE" },
    { name: "Violeta escuro", hex: "#9400D3" },
    { name: "Vinho", hex: "#722F37" }
];
